JavaScript capstone project
SamanAtashi/JS-Capstone-project pull request #34
Opened 2021-08-12 14:18 UTC by SamanAtashi

# JavaScript capstone project: API-based web app
Features are as follows:
- Use JavaScript to make websites dynamic and build basic single-page apps.
- Use ES6 syntax.
- Use ES6 modules.
- Use callbacks and promises.
- Use webpack.
- Apply JavaScript best practices and language style guides in code.
- Use the AAA pattern for unit tests.
- Write units tests for a JavaScript app.
- Follow Gitflow.
- Solve simple git conflicts.
- Send and receive data from an API.
- Use API TVmaze documentation.
- Understand and use JSON.
- Make JavaScript code synchronous.

2021-08-12 16:12 UTC, hemant-soni-vst-au4 requested changes
Hi @SamanAtashi and @andersonlebon, 

Good job so far! 👍 You guys have done superb work. 👏 
### Let me list some of the highlights
- Very organized codebase
- Good use of the Involvement API to record the different user interactions
- Awesome UI
- Good presentation of features of the project
- Good README documentation 
- Usage of Github Pages to deploy the application


There are some issues that you still need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 16:12 UTC, hemant-soni-vst-au4 commented on src/js/comments.js
> +} </p>
- [ ] As per the requirements of the project, When the `Comments popup` loads, the web app is expected to retrieve data from the selected API and show details about the selected item. And likewise, retrieve data from the [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item comments. Now we have only updated the number of comments. We should display the comments also. Let's try to fix this issue.

yours
![image](https://user-images.githubusercontent.com/53019916/129229806-827120e2-5b5c-44de-90b3-c75cdd2dc3fb.png)

Original example
![image](https://user-images.githubusercontent.com/53019916/129229940-95e19f2f-feee-4df6-8f61-62b555f4c625.png)

2021-08-12 16:12 UTC, hemant-soni-vst-au4 commented on src/js/index.js
> +  // bring them in
- [ ] Kindly try to delete the comments from the `index.js` file.

2021-08-12 16:12 UTC, hemant-soni-vst-au4 commented on src/sass/style.scss
> +//   color: rgb(48, 48, 48);
- [ ] Kindly try to delete the commented part from the file.

2021-08-13 09:02 UTC, Dipeshtwis requested changes
Hi @SamanAtashi and @andersonlebon, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 09:02 UTC, Dipeshtwis commented on src/sass/style.scss
> +// font-family: 'IBM Plex Sans Condensed', sans-serif;
- [ ] Still, I can see the commented code. Please remove that to make the codebase more cleaner.

2021-08-13 09:02 UTC, Dipeshtwis commented on src/sass/style.scss
> +// }
- [ ] Same case here, try removing all the commented code for a cleaner codebase.

2021-08-13 09:40 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 14:34 UTC, merged